config/routes.rb
Rails.application.routes.draw do

  resource :sessions, only: %i(new create destroy)

  resource :users, only: %i(new create destroy)

  root 'pictures#index'
  get 'pictures' => 'pictures#index'

  post 'pictures' => 'pictures#create'
  get 'pictures/new' => 'pictures#new'

  get 'pictures/:id/edit' => 'pictures#edit'
  patch 'pictures/:id' => 'pictures#update'

  delete 'pictures/:id' => 'pictures#destroy'

  get 'pictures/:id' => 'pictures#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord

  belongs_to :user
  
  validates :artist, presence: true
  validates :title, length: {minimum: 3, maximum: 20}
  validates :url, uniqueness: true
  validates :url, presence: true


  def self.newest_first
    Picture.order("created_at DESC")
  end

  def self.most_recent_five
    Picture.newest_first.limit(5)
  end

  def self.created_before(time)
    Picture.where("created_at < ?", time)
  end

  def self.pictures_created_in_year(year)
    Picture.where("created_at < ?", year)
  end

end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  has_many :pictures
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_sessions_url
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

before_action :ensure_logged_in, except: [:show, :index]
before_action :load_picture, only: [:show, :edit, :update, :destroy]
before_action :ensure_user_owns_picture, only: [:edit, :update, :destroy]

  def index
    month = 1.month.ago
    year = 1.year.ago
    @most_recent_pictures = Picture.most_recent_five
    @created_before = Picture.created_before(month)
    @pictures = Picture.all
    @pictures_created_in_year = Picture.pictures_created_in_year(year)
  end

  def show
  end

  def new
    @picture = Picture.new
  end

  def create

    @picture = Picture.new
    @picture.user = current_user
    @picture.title = params[:picture][:title]
    @picture.artist = params[:picture][:artist]
    @picture.url = params[:picture][:url]


    if @picture.save
      redirect_to "/pictures"
    else
      render :new
    end
  end

  def edit
  end

  def update

    @picture.title = params[:picture][:title]
    @picture.artist = params[:picture][:artist]
    @picture.url = params[:picture][:url]

    if @picture.save
      redirect_to "/pictures/#{@picture.id}"
    else
      render :edit
    end
  end

  def destroy

    @picture.destroy
    redirect_to "/pictures"
  end

  def ensure_user_owns_picture
    unless current_user == @picture.user_id
      flash[:alert] = "Please log in"
      redirect_to new_sessions_url
    end
  end

  def load_picture
    @picture = Picture.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to pictures_url, notice: "Logged in!"
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to pictures_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.save
      redirect_to root_url
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] %>

<%= yield %>

<p class="userinfo">
 <% if current_user %>
   Signed in as <%= current_user.email %>. <%= link_to "Log out", sessions_path("current"), :method => :delete %>
 <% else %>
   <%= link_to "Log in", new_sessions_path %> or <%= link_to "Sign up", new_users_path %>
 <% end %>
</p>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>

<% if @picture.errors.any? %>
  <div id="error_explanation">
    <h2>Yarr, <%= pluralize(@picture.errors.count, "error") %> be found in yer form! Try again or walk the plank, ya scurvy dog!</h2>

    <ul>
    <% @picture.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= link_to("Back", "/pictures/#{@picture.id}") %>
</p>

<%= form_for(@picture, url: "/pictures/#{@picture.id}") do |f| %>
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/pictures/index.html.erb
<h1>Pictures (<%= @pictures.length %>)</h1>

<%= link_to "New User", new_users_path %>
|
<%= link_to "Login", new_sessions_path %>
|
<%= link_to "Logout", sessions_path %>
<br><br><br>
<%= link_to("New Picture", "/pictures/new") %>

<% @pictures.each do |picture| %>
  <p><%= picture.title %>, <%= picture.artist %></p>
  <%= link_to(image_tag(picture.url), "/pictures/#{picture.id}") %>
<% end %>

<h1>Most Recent Pictures </h1>

<ul>
  <% @most_recent_pictures.each do |picture| %>
    <li><%= picture.title %></li>
  <% end %>
</ul>

<h1>Older Pictures (<%= @created_before.length %>)</h1>

<ul>
  <% @created_before.each do |picture| %>
    <li><%= picture.title %></li>
  <% end %>
</ul>

<h1>2017 Pictures (<%= @pictures_created_in_year.length %>)</h1>

<ul>
  <% @pictures_created_in_year.each do |picture| %>
    <li><%= picture.title %></li>
  <% end %>
</ul>

app/views/pictures/new.html.erb
<h1>Add a picture</h1>

<% if @picture.errors.any? %>
  <div id="error_explanation">
    <h2>Har har har! You got <%= pluralize(@picture.errors.count, "error") %> in yer little form there, matey!</h2>

    <ul>
    <% @picture.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= link_to("Back to Pictures", "/pictures") %>

<%= form_for(@picture) do |f| %>
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/pictures/show.html.erb
<%= link_to("Back to Pictures", "/pictures") %> | <%= link_to("Edit", "/pictures/#{@picture.id}/edit") %> | <%= link_to("Delete", "/pictures/#{@picture.id}", method: :delete, data: {confirm: "Are you sure you want to delete this picture?"})  %>



<p><%= @picture.title %>, <%= @picture.artist %></p>
<%= image_tag(@picture.url) %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/form.html.erb
<h1>New User Form</h1>

app/views/users/new.html.erb
<h1>New User Form</h1>


<%= form_for @user do |f| %>
<p>
<%= f.label :email %>
<%= f.text_field :email  %>
</p>
<p>
<%= f.label :password %>
<%= f.text_field :password %>
</p>
<p>
<%= f.label :password_confirmation %>
<%= f.text_field :password_confirmation %>
</p>
<%= f.submit %>

<% end %>